# Generated by Django 4.1 on 2023-07-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_history',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pdf_history',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
